---
title: "duplication"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

dictionary <- read.csv("dictionary.csv")

flight %>% 
  select(FL_DATE, CARRIER, ORIGIN, ORIGIN_CITY_NAME, ORIGIN_STATE_ABR, DEP_DELAY, DEP_TIME, ARR_DELAY, ARR_TIME) %>%
  filter(CARRIER == "UA")

dictionary <- dictionary %>%
  filter(Form.Name == "mental_health_history")

base <- dictionary[28:41,]

neurodevelopmental <- base
neurodevelopmental$Section.Header<- gsub('Neurodevelopmental', 'Neurodevelopmental Disorder(s) (e.g., Attention-Deficit/Hyperactivity Disorder)', neurodevelopmental$Section.Header)


schizophrenia <- base
schizophrenia$Variable...Field.Name <- gsub('neurodevelopmental', 'schizophrenia', schizophrenia$Variable...Field.Name)
schizophrenia$Field.Label <- gsub('neurodevelopmental', 'schizophrenia', schizophrenia$Field.Label)
schizophrenia$Branching.Logic..Show.field.only.if.... <- gsub('neurodevelopmental', 'schizophrenia', schizophrenia$Branching.Logic..Show.field.only.if....)
schizophrenia$Section.Header<- gsub('Neurodevelopmental', 'Schizophrenia Spectrum and other Psychotic Disorder(s) (e.g., Schizophrenia)', schizophrenia$Section.Header)


bipolar <- base
bipolar$Variable...Field.Name <- gsub('neurodevelopmental', 'bipolar', bipolar$Variable...Field.Name)
bipolar$Field.Label <- gsub('neurodevelopmental', 'bipolar', bipolar$Field.Label)
bipolar$Branching.Logic..Show.field.only.if.... <- gsub('neurodevelopmental', 'bipolar', bipolar$Branching.Logic..Show.field.only.if....)
bipolar$Section.Header<- gsub('Neurodevelopmental', 'Bipolar and Related Disorder(s) (e.g., Bipolar I Disorder)', bipolar$Section.Header)


depressive <- base
depressive$Variable...Field.Name <- gsub('neurodevelopmental', 'depressive', depressive$Variable...Field.Name)
depressive$Field.Label <- gsub('neurodevelopmental', 'depressive', depressive$Field.Label)
depressive$Branching.Logic..Show.field.only.if.... <- gsub('neurodevelopmental', 'depressive', depressive$Branching.Logic..Show.field.only.if....)
depressive$Section.Header<- gsub('Neurodevelopmental', 'Depressive Disorder(s) (e.g., Major Depressive Disorder)', depressive$Section.Header)


anxiety <- base
anxiety$Variable...Field.Name <- gsub('neurodevelopmental', 'anxiety', anxiety$Variable...Field.Name)
anxiety$Field.Label <- gsub('neurodevelopmental', 'anxiety', anxiety$Field.Label)
anxiety$Branching.Logic..Show.field.only.if.... <- gsub('neurodevelopmental', 'anxiety', anxiety$Branching.Logic..Show.field.only.if....)
anxiety$Section.Header<- gsub('Neurodevelopmental',	'Anxiety Disorder(s) (e.g., Social Anxiety Disorder)', anxiety$Section.Header)


ocd <- base
ocd$Variable...Field.Name <- gsub('neurodevelopmental', 'ocd', ocd$Variable...Field.Name)
ocd$Field.Label <- gsub('neurodevelopmental', 'ocd', ocd$Field.Label)
ocd$Branching.Logic..Show.field.only.if.... <- gsub('neurodevelopmental', 'ocd', ocd$Branching.Logic..Show.field.only.if....)
ocd$Section.Header<- gsub('Neurodevelopmental', 'Obsessive-Compulsive and Related Disorder(s) (e.g., Obsessive-Compulsive Disorder)', ocd$Section.Header)


trauma <- base
trauma$Variable...Field.Name <- gsub('neurodevelopmental', 'trauma', trauma$Variable...Field.Name)
trauma$Field.Label <- gsub('neurodevelopmental', 'trauma', trauma$Field.Label)
trauma$Branching.Logic..Show.field.only.if.... <- gsub('neurodevelopmental', 'trauma', trauma$Branching.Logic..Show.field.only.if....)
trauma$Section.Header<- gsub('Neurodevelopmental', 'Trauma-and-Stressor-Related Disorder(s) (e.g., Posttraumatic Stress Disorder)', trauma$Section.Header)


dissociative <- base
dissociative$Variable...Field.Name <- gsub('neurodevelopmental', 'dissociative', dissociative$Variable...Field.Name)
dissociative$Field.Label <- gsub('neurodevelopmental', 'dissociative', dissociative$Field.Label)
dissociative$Branching.Logic..Show.field.only.if.... <- gsub('neurodevelopmental', 'dissociative', dissociative$Branching.Logic..Show.field.only.if....)
dissociative$Section.Header<- gsub('Neurodevelopmental', 'Dissociative Disorder(s) (e.g., Dissociative Amnesia)', dissociative$Section.Header)


somatic <- base
somatic$Variable...Field.Name <- gsub('neurodevelopmental', 'somatic', somatic$Variable...Field.Name)
somatic$Field.Label <- gsub('neurodevelopmental', 'somatic', somatic$Field.Label)
somatic$Branching.Logic..Show.field.only.if.... <- gsub('neurodevelopmental', 'somatic', somatic$Branching.Logic..Show.field.only.if....)
somatic$Section.Header<- gsub('Neurodevelopmental', 'Somatic Symptom and Related Disorder(s) (e.g., Illness Anxiety Disorder)', somatic$Section.Header)


eating <- base
eating$Variable...Field.Name <- gsub('neurodevelopmental', 'eating', eating$Variable...Field.Name)
eating$Field.Label <- gsub('neurodevelopmental', 'eating', eating$Field.Label)
eating$Branching.Logic..Show.field.only.if.... <- gsub('neurodevelopmental', 'eating', eating$Branching.Logic..Show.field.only.if....)
eating$Section.Header<- gsub('Neurodevelopmental', 'Feeding and Eating Disorder(s) (e.g., Anorexia Nervosa)', eating$Section.Header)


elimination <- base
elimination$Variable...Field.Name <- gsub('neurodevelopmental', 'elimination', elimination$Variable...Field.Name)
elimination$Field.Label <- gsub('neurodevelopmental', 'elimination', elimination$Field.Label)
elimination$Branching.Logic..Show.field.only.if.... <- gsub('neurodevelopmental', 'elimination', elimination$Branching.Logic..Show.field.only.if....)
elimination$Section.Header<- gsub('Neurodevelopmental', 'Elimination Disorder(s) (e.g., Enuresis)	', elimination$Section.Header)


sleep <- base
sleep$Variable...Field.Name <- gsub('neurodevelopmental', 'sleep', sleep$Variable...Field.Name)
sleep$Field.Label <- gsub('neurodevelopmental', 'sleep', sleep$Field.Label)
sleep$Branching.Logic..Show.field.only.if.... <- gsub('neurodevelopmental', 'sleep', sleep$Branching.Logic..Show.field.only.if....)
sleep$Section.Header<- gsub('Neurodevelopmental', 'Sleep-Wake Disorder(s) (e.g., Insomnia)', sleep$Section.Header)


sexual <- base
sexual$Variable...Field.Name <- gsub('neurodevelopmental', 'sexual', sexual$Variable...Field.Name)
sexual$Field.Label <- gsub('neurodevelopmental', 'sexual', sexual$Field.Label)
sexual$Branching.Logic..Show.field.only.if.... <- gsub('neurodevelopmental', 'sexual', sexual$Branching.Logic..Show.field.only.if....)
sexual$Section.Header<- gsub('Neurodevelopmental', 'Sexual Dysfunction(s) (e.g., Erectile Disorder)', sexual$Section.Header)


gender <- base
gender$Variable...Field.Name <- gsub('neurodevelopmental', 'gender', gender$Variable...Field.Name)
gender$Field.Label <- gsub('neurodevelopmental', 'gender', gender$Field.Label)
gender$Branching.Logic..Show.field.only.if.... <- gsub('neurodevelopmental', 'gender', gender$Branching.Logic..Show.field.only.if....)
gender$Section.Header<- gsub('Neurodevelopmental', 'Gender Dysphoria', gender$Section.Header)


disruptive <- base
disruptive$Variable...Field.Name <- gsub('neurodevelopmental', 'disruptive', disruptive$Variable...Field.Name)
disruptive$Field.Label <- gsub('neurodevelopmental', 'disruptive', disruptive$Field.Label)
disruptive$Branching.Logic..Show.field.only.if.... <- gsub('neurodevelopmental', 'disruptive', disruptive$Branching.Logic..Show.field.only.if....)
disruptive$Section.Header<- gsub('Neurodevelopmental', 'Disruptive, Impulse-Control, and Conduct Disorder(s) (e.g., Oppositional-Defiant Disorder)', disruptive$Section.Header)


substance <- base
substance$Variable...Field.Name <- gsub('neurodevelopmental', 'substance', substance$Variable...Field.Name)
substance$Field.Label <- gsub('neurodevelopmental', 'substance', substance$Field.Label)
substance$Branching.Logic..Show.field.only.if.... <- gsub('neurodevelopmental', 'substance', substance$Branching.Logic..Show.field.only.if....)
substance$Section.Header<- gsub('Neurodevelopmental', 'Substance-Related and Addictive Disorder(s)(e.g., Alcohol Use Disorder)', substance$Section.Header)


neurocognitive <- base
neurocognitive$Variable...Field.Name <- gsub('neurodevelopmental', 'neurocognitive', neurocognitive$Variable...Field.Name)
neurocognitive$Field.Label <- gsub('neurodevelopmental', 'neurocognitive', neurocognitive$Field.Label)
neurocognitive$Branching.Logic..Show.field.only.if.... <- gsub('neurodevelopmental', 'neurocognitive', neurocognitive$Branching.Logic..Show.field.only.if....)
neurocognitive$Section.Header<- gsub('Neurodevelopmental', 'Neurocognitive Disorder(s) (e.g., Delirium)', neurocognitive$Section.Header)


personality <- base
personality$Variable...Field.Name <- gsub('neurodevelopmental', 'personality', personality$Variable...Field.Name)
personality$Field.Label <- gsub('neurodevelopmental', 'personality', personality$Field.Label)
personality$Branching.Logic..Show.field.only.if.... <- gsub('neurodevelopmental', 'personality', personality$Branching.Logic..Show.field.only.if....)
personality$Section.Header<- gsub('Neurodevelopmental', 'Personality Disorder(s) (e.g., Borderline Personality Disorder)', personality$Section.Header)


paraphilic <- base
paraphilic$Variable...Field.Name <- gsub('neurodevelopmental', 'paraphilic', paraphilic$Variable...Field.Name)
paraphilic$Field.Label <- gsub('neurodevelopmental', 'paraphilic', paraphilic$Field.Label)
paraphilic$Branching.Logic..Show.field.only.if.... <- gsub('neurodevelopmental', 'paraphilic', paraphilic$Branching.Logic..Show.field.only.if....)
paraphilic$Section.Header<- gsub('Neurodevelopmental', 'Paraphilic Disorder(s) (e.g., Exhibitionistic Disorder)', paraphilic$Section.Header)


other <- base
other$Variable...Field.Name <- gsub('neurodevelopmental', 'other', other$Variable...Field.Name)
other$Field.Label <- gsub('neurodevelopmental', 'other', other$Field.Label)
other$Branching.Logic..Show.field.only.if.... <- gsub('neurodevelopmental', 'other', other$Branching.Logic..Show.field.only.if....)
other$Section.Header<- gsub('Neurodevelopmental', 'Other', other$Section.Header)

compiled <- rbind(neurodevelopmental, schizophrenia, bipolar, depressive, anxiety, ocd, trauma, dissociative, somatic, eating, elimination, sleep, sexual, gender, disruptive, substance, neurocognitive, personality, paraphilic, other)

write.csv(compiled, "dictionary_new.csv", row.names = FALSE, na = "")


dictionary <- dictionary[!grepl("child_4", dictionary$Variable...Field.Name),]
dictionary <- dictionary[!grepl("child_3", dictionary$Variable...Field.Name),]
dictionary <- dictionary[!grepl("child_2", dictionary$Variable...Field.Name),]

dictionary <- transform(dictionary, questionnaire_order=match(Form.Name, unique(Form.Name)))
dictionary <- transform(dictionary, variable_order=match(Variable...Field.Name, unique(Variable...Field.Name)))

#dictionary <- select(dictionary, "Variable...Field.Name", "Form.Name","Branching.Logic..Show.field.only.if....", "Section.Header", "Field.Label", "Matrix.Group.Name")

child_2 = dictionary[grep("child_1", dictionary$Variable...Field.Name),]
child_2$Variable...Field.Name <- gsub('child_1', 'child_2', child_2$Variable...Field.Name)
child_2$Branching.Logic..Show.field.only.if.... <- gsub('child_1', 'child_2', child_2$Branching.Logic..Show.field.only.if....)
child_2$Matrix.Group.Name <- gsub('child_1', 'child_2', child_2$Matrix.Group.Name)
child_2$Section.Header <- gsub('Child 1', 'Child 2', child_2$Section.Header)
child_2$Section.Header <- gsub('CHILD 1', 'CHILD 2', child_2$Section.Header)
child_2$Section.Header <- gsub('child 1', 'child 2', child_2$Section.Header)
child_2$Field.Label <- gsub('Child 1', 'Child 2', child_2$Field.Label)
child_2$Field.Label <- gsub('CHILD 1', 'CHILD 2', child_2$Field.Label)
child_2$Field.Label <- gsub('child 1', 'child 2', child_2$Field.Label)

child_3 = dictionary[grep("child_1", dictionary$Variable...Field.Name),]
child_3$Variable...Field.Name <- gsub('child_1', 'child_3', child_3$Variable...Field.Name)
child_3$Branching.Logic..Show.field.only.if.... <- gsub('child_1', 'child_3', child_3$Branching.Logic..Show.field.only.if....)
child_3$Matrix.Group.Name <- gsub('child_1', 'child_3', child_3$Matrix.Group.Name)
child_3$Section.Header <- gsub('Child 1', 'Child 3', child_3$Section.Header)
child_3$Section.Header <- gsub('CHILD 1', 'CHILD 3', child_3$Section.Header)
child_3$Section.Header <- gsub('child 1', 'child 3', child_3$Section.Header)
child_3$Field.Label <- gsub('Child 1', 'Child 3', child_3$Field.Label)
child_3$Field.Label <- gsub('CHILD 1', 'CHILD 3', child_3$Field.Label)
child_3$Field.Label <- gsub('child 1', 'child 3', child_3$Field.Label)

child_4 = dictionary[grep("child_1", dictionary$Variable...Field.Name),]
child_4$Variable...Field.Name <- gsub('child_1', 'child_4', child_4$Variable...Field.Name)
child_4$Branching.Logic..Show.field.only.if.... <- gsub('child_1', 'child_4', child_4$Branching.Logic..Show.field.only.if....)
child_4$Matrix.Group.Name <- gsub('child_1', 'child_4', child_4$Matrix.Group.Name)
child_4$Section.Header <- gsub('Child 1', 'Child 4', child_4$Section.Header)
child_4$Section.Header <- gsub('CHILD 1', 'CHILD 4', child_4$Section.Header)
child_4$Section.Header <- gsub('child 1', 'child 4', child_4$Section.Header)
child_4$Field.Label <- gsub('Child 1', 'Child 4', child_4$Field.Label)
child_4$Field.Label <- gsub('CHILD 1', 'CHILD 4', child_4$Field.Label)
child_4$Field.Label <- gsub('child 1', 'child 4', child_4$Field.Label)

dictionary$child_number <- 1
child_2$child_number <- 2
child_3$child_number <- 3
child_4$child_number <- 4

compiled <- rbind(dictionary, child_2, child_3, child_4)

#compiled %>% arrange(questionnaire_order, child_number)

#compiled$Form.Name <- relevel(compiled$Form.Name, "participant")
#compiled$Form.Name <- factor(compiled$Form.Name, levels = c("participant", "panas_1", "information", "covid_objective", "five", "soi", "gmf", "pcrq", "parenting_stress", "biq", "pbq", "tesi", "demographics", "stai", "rcads", "cshq", "ashq", "panas_2", "panas_3", "written_response_child_1"))
#fct_relevel(compiled$Form.Name)

library(tidyverse)
#compiled_sort <- compiled %>% 
#  group_by(Form.Name) %>%
#  group_by(Matrix.Group.Name) %>%
#  arrange(desc(Variable...Field.Name, .by_group = TRUE))

#compiled_sort <- compiled %>% 
#  group_by(Form.Name) %>%
#  group_by(Matrix.Group.Name) %>%
#  arrange(desc(questionnaire_order, Variable...Field.Name, .by_group = TRUE))

#compiled_sort <- compiled %>% 
#  group_by(questionnaire_order) %>%
#  group_by(Matrix.Group.Name) %>%
#  arrange(questionnaire_order, child_number, .by_group = TRUE)

compiled_sort <- compiled %>% arrange(questionnaire_order, child_number)

dictionary <- compiled_sort

dictionary$Branching.Logic..Show.field.only.if.... = as.character(dictionary$Branching.Logic..Show.field.only.if....)
dictionary$Branching.Logic..Show.field.only.if....[grepl("child_2", dictionary$Variable...Field.Name) & dictionary$Branching.Logic..Show.field.only.if.... == ""] <- "[parentself_number_children_study] = '2' or [parentself_number_children_study] = '3' or [parentself_number_children_study] = '4'"
dictionary$Branching.Logic..Show.field.only.if....[grepl("child_3", dictionary$Variable...Field.Name) & dictionary$Branching.Logic..Show.field.only.if.... == ""] <- "[parentself_number_children_study] = '3' or [parentself_number_children_study] = '4'"
dictionary$Branching.Logic..Show.field.only.if....[grepl("child_4", dictionary$Variable...Field.Name) & dictionary$Branching.Logic..Show.field.only.if.... == ""] <- "[parentself_number_children_study] = '4'"





dictionary$Branching.Logic..Show.field.only.if....[grepl("child_1", dictionary$Variable...Field.Name) & grepl("cshq", dictionary$Variable...Field.Name) & dictionary$Branching.Logic..Show.field.only.if.... == ""] <- "[child_1_age] <= 12"
dictionary$Branching.Logic..Show.field.only.if....[grepl("child_2", dictionary$Variable...Field.Name) & grepl("cshq", dictionary$Variable...Field.Name) & dictionary$Branching.Logic..Show.field.only.if.... == ""] <- "[child_2_age] <= 12 and ([parentself_number_children_study] = '2' or [parentself_number_children_study] = '3' or [parentself_number_children_study] = '4')"
dictionary$Branching.Logic..Show.field.only.if....[grepl("child_3", dictionary$Variable...Field.Name) & grepl("cshq", dictionary$Variable...Field.Name) & dictionary$Branching.Logic..Show.field.only.if.... == ""] <- "[child_3_age] <= 12 and ([parentself_number_children_study] = '3' or [parentself_number_children_study] = '4')"
dictionary$Branching.Logic..Show.field.only.if....[grepl("child_4", dictionary$Variable...Field.Name) & grepl("cshq", dictionary$Variable...Field.Name) & dictionary$Branching.Logic..Show.field.only.if.... == ""] <- "[child_4_age] <= 12 and [parentself_number_children_study] = '4'"






dictionary$Branching.Logic..Show.field.only.if....[grepl("child_1", dictionary$Variable...Field.Name) & grepl("ashq", dictionary$Variable...Field.Name) & dictionary$Branching.Logic..Show.field.only.if.... != "[ashq_1_parentproxy_child_1] = '4'" & dictionary$Branching.Logic..Show.field.only.if.... != "[ashq_17_parentproxy_child_1] = '1' or [ashq_17_parentproxy_child_1] = '2' or [ashq_17_parentproxy_child_1] = '3' or [ashq_17_parentproxy_child_1] = '4'" & dictionary$Branching.Logic..Show.field.only.if.... != "[ashq_29_parentproxy_child_1] = '1' or [ashq_29_parentproxy_child_1] = '2' or [ashq_29_parentproxy_child_1] = '3' or [ashq_29_parentproxy_child_1] = '4'"] <- "[child_1_age] > 12"

dictionary$Branching.Logic..Show.field.only.if....[grepl("child_2", dictionary$Variable...Field.Name) & grepl("ashq", dictionary$Variable...Field.Name) & dictionary$Branching.Logic..Show.field.only.if.... != "[ashq_1_parentproxy_child_1] = '4'" & dictionary$Branching.Logic..Show.field.only.if.... != "[ashq_17_parentproxy_child_2] = '1' or [ashq_17_parentproxy_child_2] = '2' or [ashq_17_parentproxy_child_2] = '3' or [ashq_17_parentproxy_child_2] = '4'" & dictionary$Branching.Logic..Show.field.only.if.... != "[ashq_29_parentproxy_child_2] = '1' or [ashq_29_parentproxy_child_2] = '2' or [ashq_29_parentproxy_child_2] = '3' or [ashq_29_parentproxy_child_2] = '4'"] <- "[child_2_age] > 12 and ([parentself_number_children_study] = '2' or [parentself_number_children_study] = '3' or [parentself_number_children_study] = '4')"

dictionary$Branching.Logic..Show.field.only.if....[grepl("child_3", dictionary$Variable...Field.Name) & grepl("ashq", dictionary$Variable...Field.Name) & dictionary$Branching.Logic..Show.field.only.if.... != "[ashq_1_parentproxy_child_1] = '4'" & dictionary$Branching.Logic..Show.field.only.if.... != "[ashq_17_parentproxy_child_3] = '1' or [ashq_17_parentproxy_child_3] = '2' or [ashq_17_parentproxy_child_3] = '3' or [ashq_17_parentproxy_child_3] = '4'" & dictionary$Branching.Logic..Show.field.only.if.... != "[ashq_29_parentproxy_child_3] = '1' or [ashq_29_parentproxy_child_3] = '2' or [ashq_29_parentproxy_child_3] = '3' or [ashq_29_parentproxy_child_3] = '4'"] <-"[child_3_age] > 12 and ([parentself_number_children_study] = '3' or [parentself_number_children_study] = '4')"

dictionary$Branching.Logic..Show.field.only.if....[grepl("child_4", dictionary$Variable...Field.Name) & grepl("ashq", dictionary$Variable...Field.Name) & dictionary$Branching.Logic..Show.field.only.if.... != "[ashq_1_parentproxy_child_1] = '4'" & dictionary$Branching.Logic..Show.field.only.if.... != "[ashq_17_parentproxy_child_4] = '1' or [ashq_17_parentproxy_child_4] = '2' or [ashq_17_parentproxy_child_4] = '3' or [ashq_17_parentproxy_child_4] = '4'" & dictionary$Branching.Logic..Show.field.only.if.... != "[ashq_29_parentproxy_child_4] = '1' or [ashq_29_parentproxy_child_4] = '2' or [ashq_29_parentproxy_child_4] = '3' or [ashq_29_parentproxy_child_4] = '4'"] <- "[child_4_age] > 12 and [parentself_number_children_study] = '4'"







dictionary$Branching.Logic..Show.field.only.if....[grepl("child_2", dictionary$Variable...Field.Name) & grepl("five", dictionary$Form.Name)] <- "([parentself_number_children_study] = '2'  or [parentself_number_children_study] = '3'  or [parentself_number_children_study] = '4') and [five_parentproxy_continue] = '1'"
dictionary$Branching.Logic..Show.field.only.if....[grepl("child_3", dictionary$Variable...Field.Name) & grepl("five", dictionary$Form.Name)] <- "([parentself_number_children_study] = '3'  or [parentself_number_children_study] = '4') and [five_parentproxy_continue] = '1'"
dictionary$Branching.Logic..Show.field.only.if....[grepl("child_4", dictionary$Variable...Field.Name) & grepl("five", dictionary$Form.Name)] <- "([parentself_number_children_study] = '4') and [five_parentproxy_continue] = '1'"

dictionary$Branching.Logic..Show.field.only.if....[grepl("child_2", dictionary$Variable...Field.Name) & grepl("soi", dictionary$Form.Name)] <- "([parentself_number_children_study] = '2'  or [parentself_number_children_study] = '3'  or [parentself_number_children_study] = '4') and [soi_parentproxy_continue] = '1'"
dictionary$Branching.Logic..Show.field.only.if....[grepl("child_3", dictionary$Variable...Field.Name) & grepl("soi", dictionary$Form.Name)] <- "([parentself_number_children_study] = '3'  or [parentself_number_children_study] = '4') and [soi_parentproxy_continue] = '1'"
dictionary$Branching.Logic..Show.field.only.if....[grepl("child_4", dictionary$Variable...Field.Name) & grepl("soi", dictionary$Form.Name)] <- "([parentself_number_children_study] = '4') and [soi_parentproxy_continue] = '1'"



dictionary$Branching.Logic..Show.field.only.if....[grepl("child_2", dictionary$Variable...Field.Name) & grepl("tesi", dictionary$Form.Name) & dictionary$Branching.Logic..Show.field.only.if.... == "[parentself_number_children_study] = '2' or [parentself_number_children_study] = '3' or [parentself_number_children_study] = '4'"] <- "([parentself_number_children_study] = '2'  or [parentself_number_children_study] = '3'  or [parentself_number_children_study] = '4') and [tesi_parentproxy_continue] = '1'"

dictionary$Branching.Logic..Show.field.only.if....[grepl("child_3", dictionary$Variable...Field.Name) & grepl("tesi", dictionary$Form.Name) & dictionary$Branching.Logic..Show.field.only.if.... == "[parentself_number_children_study] = '3' or [parentself_number_children_study] = '4'"] <- "([parentself_number_children_study] =  '3'  or [parentself_number_children_study] = '4') and [tesi_parentproxy_continue] = '1'"

dictionary$Branching.Logic..Show.field.only.if....[grepl("child_4", dictionary$Variable...Field.Name) & grepl("tesi", dictionary$Form.Name) & dictionary$Branching.Logic..Show.field.only.if.... == "[parentself_number_children_study] = '4'"] <- "([parentself_number_children_study] = '4') and [tesi_parentproxy_continue] = '1'"



dictionary$Branching.Logic..Show.field.only.if....[grepl("child_2", dictionary$Variable...Field.Name) & grepl("demographics", dictionary$Form.Name) & dictionary$Branching.Logic..Show.field.only.if.... == "[parentself_number_children_study] = '2' or [parentself_number_children_study] = '3' or [parentself_number_children_study] = '4'"] <- "([parentself_number_children_study] = '2'  or [parentself_number_children_study] = '3'  or [parentself_number_children_study] = '4') and [demographics_parentproxy_continue] = '1'"

dictionary$Branching.Logic..Show.field.only.if....[grepl("child_3", dictionary$Variable...Field.Name) & grepl("demographics", dictionary$Form.Name) & dictionary$Branching.Logic..Show.field.only.if.... == "[parentself_number_children_study] = '3' or [parentself_number_children_study] = '4'"] <- "([parentself_number_children_study] =  '3'  or [parentself_number_children_study] = '4') and [demographics_parentproxy_continue] = '1'"

dictionary$Branching.Logic..Show.field.only.if....[grepl("child_4", dictionary$Variable...Field.Name) & grepl("demographics", dictionary$Form.Name) & dictionary$Branching.Logic..Show.field.only.if.... == "[parentself_number_children_study] = '4'"] <- "([parentself_number_children_study] = '4') and [demographics_parentproxy_continue] = '1'"


write.csv(dictionary, "dictionary_new.csv", row.names = FALSE, na = "")
#write.csv(dictionary_2, "dictionary_2.csv", row.names = FALSE, na = "")

```

